// This file is auto-generated by @hey-api/openapi-ts

export type AnnouncementsPublic = {
    data: Array<app__models__announcement__AnnouncementPublic>;
    count: number;
};

export type app__models__announcement__AnnouncementCreate = {
    title: string;
    description?: (string | null);
    category: string;
    requires_coupon?: boolean;
    campaign_id?: (string | null);
    is_published?: boolean;
    publish_date?: (string | null);
    created_date?: (string | null);
    expiry_date?: (string | null);
};

export type app__models__announcement__AnnouncementPublic = {
    title: string;
    description?: (string | null);
    category: string;
    requires_coupon?: boolean;
    campaign_id?: (string | null);
    is_published?: boolean;
    publish_date?: (string | null);
    created_date: (string | null);
    expiry_date: (string | null);
    id: string;
    deleted_at?: (string | null);
};

export type app__models__announcement__AnnouncementUpdate = {
    title?: (string | null);
    description?: (string | null);
    category?: (string | null);
    requires_coupon?: (boolean | null);
    campaign_id?: (string | null);
    is_published?: (boolean | null);
    publish_date?: (string | null);
    created_date?: (string | null);
    expiry_date?: (string | null);
};

export type app__models__user__UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    keycloak_user_id?: (string | null);
    id: string;
};

export type app__schemas__announcement__AnnouncementCreate = {
    title: string;
    description?: (string | null);
    category: string;
    requires_coupon?: boolean;
    campaign_id?: (string | null);
    is_published?: boolean;
    publish_date?: (string | null);
    expires_at?: (string | null);
};

export type app__schemas__announcement__AnnouncementPublic = {
    title: string;
    description: (string | null);
    category: string;
    requires_coupon: boolean;
    campaign_id: (string | null);
    is_published: boolean;
    publish_date: (string | null);
    expires_at: (string | null);
    id: string;
};

export type app__schemas__announcement__AnnouncementUpdate = {
    title?: (string | null);
    description?: (string | null);
    category?: (string | null);
    requires_coupon?: (boolean | null);
    campaign_id?: (string | null);
    is_published?: (boolean | null);
    publish_date?: (string | null);
    expires_at?: (string | null);
};

export type app__schemas__user__UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    keycloak_user_id?: (string | null);
    id: number;
};

export type CampaignCreate = {
    name: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    is_active?: boolean;
};

export type CampaignPublic = {
    name: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    is_active?: boolean;
    id: string;
    created_at: string;
};

export type CampaignsPublic = {
    data: Array<CampaignPublic>;
    count: number;
};

export type CampaignUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: (boolean | null);
};

export type CouponCreate = {
    code: string;
    discount_type: string;
    discount_value: number;
    campaign_id?: (string | null);
    assigned_user_id?: (string | null);
    redeemed?: boolean;
    redeemed_at?: (string | null);
    expires_at?: (string | null);
};

export type CouponPublic = {
    code: string;
    discount_type: string;
    discount_value: number;
    campaign_id?: (string | null);
    assigned_user_id?: (string | null);
    redeemed?: boolean;
    redeemed_at?: (string | null);
    expires_at?: (string | null);
    id: string;
    created_at: string;
};

export type CouponsPublic = {
    data: Array<CouponPublic>;
    count: number;
};

export type CouponUpdate = {
    code?: (string | null);
    discount_type?: (string | null);
    discount_value?: (number | null);
    campaign_id?: (string | null);
    assigned_user_id?: (string | null);
    redeemed?: (boolean | null);
    redeemed_at?: (string | null);
    expires_at?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    full_name: string;
    is_verified?: boolean;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    keycloak_user_id?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<app__schemas__user__UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    keycloak_user_id?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AdminAnnouncementsAnnouncementsOptionsResponse = (unknown);

export type AdminAnnouncementsGetAllAnnouncementsData = {
    category?: (string | null);
    newCategory?: boolean;
    search?: (string | null);
};

export type AdminAnnouncementsGetAllAnnouncementsResponse = ({
    [key: string]: unknown;
});

export type AdminAnnouncementsCreateAnnouncementData = {
    requestBody: app__schemas__announcement__AnnouncementCreate;
};

export type AdminAnnouncementsCreateAnnouncementResponse = (app__schemas__announcement__AnnouncementPublic);

export type AdminAnnouncementsAnnouncementItemOptionsResponse = (unknown);

export type AdminAnnouncementsGetAnnouncementByIdData = {
    announcementId: string;
};

export type AdminAnnouncementsGetAnnouncementByIdResponse = (app__schemas__announcement__AnnouncementPublic);

export type AdminAnnouncementsUpdateAnnouncementData = {
    announcementId: string;
    requestBody: app__schemas__announcement__AnnouncementUpdate;
};

export type AdminAnnouncementsUpdateAnnouncementResponse = (app__schemas__announcement__AnnouncementPublic);

export type AdminAnnouncementsDeleteAnnouncementData = {
    announcementId: string;
};

export type AdminAnnouncementsDeleteAnnouncementResponse = ({
    [key: string]: unknown;
});

export type AdminCampaignsGetAllCampaignsData = {
    category?: (string | null);
    search?: (string | null);
};

export type AdminCampaignsGetAllCampaignsResponse = ({
    [key: string]: unknown;
});

export type AdminCampaignsCreateCampaignData = {
    requestBody: CampaignCreate;
};

export type AdminCampaignsCreateCampaignResponse = ({
    [key: string]: unknown;
});

export type AdminCampaignsGetCampaignData = {
    campaignId: string;
};

export type AdminCampaignsGetCampaignResponse = ({
    [key: string]: unknown;
});

export type AdminCampaignsUpdateCampaignData = {
    campaignId: string;
    requestBody: CampaignUpdate;
};

export type AdminCampaignsUpdateCampaignResponse = ({
    [key: string]: unknown;
});

export type AdminCampaignsDeleteCampaignData = {
    campaignId: string;
};

export type AdminCampaignsDeleteCampaignResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsGetAllCouponsData = {
    assignedUserId?: (string | null);
    campaignId?: (string | null);
    category?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type AdminCouponsGetAllCouponsResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsCreateCouponData = {
    requestBody: CouponCreate;
};

export type AdminCouponsCreateCouponResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsGetCouponData = {
    couponId: string;
};

export type AdminCouponsGetCouponResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsUpdateCouponData = {
    couponId: string;
    requestBody: CouponUpdate;
};

export type AdminCouponsUpdateCouponResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsDeleteCouponData = {
    couponId: string;
};

export type AdminCouponsDeleteCouponResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsGenerateCouponsData = {
    campaignId: string;
    count: number;
};

export type AdminCouponsGenerateCouponsResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsAssignCampaignToAllUsersData = {
    campaignId: string;
};

export type AdminCouponsAssignCampaignToAllUsersResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsAssignCouponToUserData = {
    couponId: string;
    userId: string;
};

export type AdminCouponsAssignCouponToUserResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsGetUnassignedCouponsData = {
    campaignId: string;
};

export type AdminCouponsGetUnassignedCouponsResponse = ({
    [key: string]: unknown;
});

export type AdminCouponsGetCampaignCouponStatsData = {
    campaignId: string;
};

export type AdminCouponsGetCampaignCouponStatsResponse = ({
    [key: string]: unknown;
});

export type AnnouncementsAnnouncementsOptionsResponse = (unknown);

export type AnnouncementsCreateAnnouncementEndpointData = {
    requestBody: app__models__announcement__AnnouncementCreate;
};

export type AnnouncementsCreateAnnouncementEndpointResponse = (app__models__announcement__AnnouncementPublic);

export type AnnouncementsReadAnnouncementsData = {
    category?: (string | null);
    limit?: number;
    /**
     * Include announcements created in the last 10 days
     */
    newCategory?: boolean;
    search?: (string | null);
    skip?: number;
};

export type AnnouncementsReadAnnouncementsResponse = (AnnouncementsPublic);

export type AnnouncementsReadPublishedAnnouncementsData = {
    category?: (string | null);
    limit?: number;
    /**
     * Include announcements created in the last 10 days
     */
    newCategory?: boolean;
    search?: (string | null);
    skip?: number;
};

export type AnnouncementsReadPublishedAnnouncementsResponse = (AnnouncementsPublic);

export type AnnouncementsReadAnnouncementData = {
    id: string;
};

export type AnnouncementsReadAnnouncementResponse = (app__models__announcement__AnnouncementPublic);

export type AnnouncementsUpdateAnnouncementEndpointData = {
    id: string;
    requestBody: app__models__announcement__AnnouncementUpdate;
};

export type AnnouncementsUpdateAnnouncementEndpointResponse = (app__models__announcement__AnnouncementPublic);

export type AnnouncementsDeleteAnnouncementEndpointData = {
    id: string;
};

export type AnnouncementsDeleteAnnouncementEndpointResponse = (Message);

export type CampaignsCreateCampaignEndpointData = {
    requestBody: CampaignCreate;
};

export type CampaignsCreateCampaignEndpointResponse = (CampaignPublic);

export type CampaignsReadCampaignsData = {
    limit?: number;
    skip?: number;
};

export type CampaignsReadCampaignsResponse = (CampaignsPublic);

export type CampaignsReadCampaignData = {
    id: string;
};

export type CampaignsReadCampaignResponse = (CampaignPublic);

export type CampaignsUpdateCampaignEndpointData = {
    id: string;
    requestBody: CampaignCreate;
};

export type CampaignsUpdateCampaignEndpointResponse = (CampaignPublic);

export type CampaignsDeleteCampaignEndpointData = {
    id: string;
};

export type CampaignsDeleteCampaignEndpointResponse = (Message);

export type CouponsCouponsOptionsResponse = (unknown);

export type CouponsCreateCouponEndpointData = {
    requestBody: CouponCreate;
};

export type CouponsCreateCouponEndpointResponse = (CouponPublic);

export type CouponsReadCouponsData = {
    limit?: number;
    skip?: number;
};

export type CouponsReadCouponsResponse = (CouponsPublic);

export type CouponsReadUserCouponsResponse = (CouponsPublic);

export type CouponsUserCouponsOptionsResponse = (unknown);

export type CouponsCouponOptionsData = {
    id: string;
};

export type CouponsCouponOptionsResponse = (unknown);

export type CouponsReadCouponData = {
    id: string;
};

export type CouponsReadCouponResponse = (CouponPublic);

export type CouponsUpdateCouponEndpointData = {
    id: string;
    requestBody: CouponCreate;
};

export type CouponsUpdateCouponEndpointResponse = (CouponPublic);

export type CouponsDeleteCouponEndpointData = {
    id: string;
};

export type CouponsDeleteCouponEndpointResponse = (Message);

export type CouponsRedeemCouponOptionsData = {
    id: string;
};

export type CouponsRedeemCouponOptionsResponse = (unknown);

export type CouponsRedeemCouponEndpointData = {
    id: string;
};

export type CouponsRedeemCouponEndpointResponse = (CouponPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (app__models__user__UserPublic);

export type UserCouponsGetMyCouponsResponse = ({
    [key: string]: unknown;
});

export type UserCouponsRedeemCouponData = {
    couponId: string;
};

export type UserCouponsRedeemCouponResponse = ({
    [key: string]: unknown;
});

export type UserCouponsGetCouponData = {
    couponId: string;
};

export type UserCouponsGetCouponResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (app__models__user__UserPublic);

export type UsersReadUserMeResponse = (app__models__user__UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (app__models__user__UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (app__models__user__UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (app__models__user__UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (app__models__user__UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);