version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - NODE_ENV=production
    image: kurumsal-indirim-frontend:${TAG:-latest}
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge