"""Add keycloak_user_id to user table

Revision ID: f0a5b3c4d7e8
Revises: 9c0a54914c78
Create Date: 2025-12-16 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0a5b3c4d7e8'
down_revision = '9c0a54914c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('keycloak_user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_keycloak_user_id'), 'user', ['keycloak_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_keycloak_user_id'), table_name='user')
    op.drop_column('user', 'keycloak_user_id')
    # ### end Alembic commands ###