/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCouponsIndexRouteImport } from './routes/_layout/coupons/index'
import { Route as LayoutCampaignsIndexRouteImport } from './routes/_layout/campaigns/index'
import { Route as LayoutAnnouncementsIndexRouteImport } from './routes/_layout/announcements/index'
import { Route as LayoutAnnouncementsIdRouteImport } from './routes/_layout/announcements/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/_layout/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/_layout/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCouponsIndexRoute = LayoutCouponsIndexRouteImport.update({
  id: '/_layout/coupons/',
  path: '/coupons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCampaignsIndexRoute = LayoutCampaignsIndexRouteImport.update({
  id: '/_layout/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAnnouncementsIndexRoute =
  LayoutAnnouncementsIndexRouteImport.update({
    id: '/_layout/announcements/',
    path: '/announcements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAnnouncementsIdRoute = LayoutAnnouncementsIdRouteImport.update({
  id: '/_layout/announcements/$id',
  path: '/announcements/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/announcements/$id': typeof LayoutAnnouncementsIdRoute
  '/announcements': typeof LayoutAnnouncementsIndexRoute
  '/campaigns': typeof LayoutCampaignsIndexRoute
  '/coupons': typeof LayoutCouponsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/announcements/$id': typeof LayoutAnnouncementsIdRoute
  '/announcements': typeof LayoutAnnouncementsIndexRoute
  '/campaigns': typeof LayoutCampaignsIndexRoute
  '/coupons': typeof LayoutCouponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/announcements/$id': typeof LayoutAnnouncementsIdRoute
  '/_layout/announcements/': typeof LayoutAnnouncementsIndexRoute
  '/_layout/campaigns/': typeof LayoutCampaignsIndexRoute
  '/_layout/coupons/': typeof LayoutCouponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/announcements/$id'
    | '/announcements'
    | '/campaigns'
    | '/coupons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/announcements/$id'
    | '/announcements'
    | '/campaigns'
    | '/coupons'
  id:
    | '__root__'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/announcements/$id'
    | '/_layout/announcements/'
    | '/_layout/campaigns/'
    | '/_layout/coupons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAnnouncementsIdRoute: typeof LayoutAnnouncementsIdRoute
  LayoutAnnouncementsIndexRoute: typeof LayoutAnnouncementsIndexRoute
  LayoutCampaignsIndexRoute: typeof LayoutCampaignsIndexRoute
  LayoutCouponsIndexRoute: typeof LayoutCouponsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/coupons/': {
      id: '/_layout/coupons/'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof LayoutCouponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/campaigns/': {
      id: '/_layout/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof LayoutCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/announcements/': {
      id: '/_layout/announcements/'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof LayoutAnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/announcements/$id': {
      id: '/_layout/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof LayoutAnnouncementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAnnouncementsIdRoute: LayoutAnnouncementsIdRoute,
  LayoutAnnouncementsIndexRoute: LayoutAnnouncementsIndexRoute,
  LayoutCampaignsIndexRoute: LayoutCampaignsIndexRoute,
  LayoutCouponsIndexRoute: LayoutCouponsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
